### ISSUE TITLE
Question: will you enable github discussions ?

### ISSUE THREAD

**Issue by veith** [outcaste-io/issues#2]
Will you enable github [discussions](https://docs.github.com/en/discussions) on the repositories?

Because opening a issue for every question is not so cool.

**Comment by manishrjain** [comment]
We'll set up a Discourse forum for Outcaste users. I believe that's the best designed tool for discussions.

**Comment by veith** [comment]
Thank you for the information.

**Comment by manishrjain** [comment]
We are not sure about the timeline for Discourse forum yet. So, for now, just ask anything here.
