### ISSUE TITLE
When build with -buildmode=plugin, go complains about an asm error

### ISSUE THREAD

**Issue by siddharthlatest** [outcaste-io/issues#22]
Any go package that depends on Badger and builds using buildmode=plugin or anything using dynamic link will see the error:

when dynamic linking, R15 is clobbered by a global variable access and is used here
To reproduce this, try the following:

git clone https://github.com/appbaseio/reactivesearch-api
make clean && make
^ The above project uses buildmode=plugin to build and badger is a dependency of it.

This is originating from cespare/xxhash module, the issue is described over here: [cespare/xxhash#54 4](https://github.com/cespare/xxhash/issues/54). It’s fixed in their latest release: v2.1.2. Updating this module to this release in badger should resolve this issue. There is also a PR in the original repo that contains the fix: https://github.com/dgraph-io/badger/pull/1777.

Further reference is here: [github.com/golang/go/issues/43661](http://github.com/golang/go/issues/43661).

Originally raised at: https://discuss.dgraph.io/t/when-build-with-buildmode-plugin-go-complains-about-an-asm-error/16341

**Comment by manishrjain** [comment]
Hey @siddharthlatest , would you like to send a PR?

**Comment by eh-steve** [comment]
Hi Manish, would you like me to open the badger PR here instead?

**Comment by manishrjain** [comment]
Yeah, that'd be great.

**Comment by eh-steve** [comment]
https://github.com/outcaste-io/badger/pull/7

**Comment by manishrjain** [comment]
This PR was merged.
