### ISSUE TITLE
BadgerDB panicked in a read-only transaction

### ISSUE THREAD

**Issue by amwolff** [outcaste-io/issues#27]
Hi everyone. I have something fun to report:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9e4feb]
goroutine 5401444 [running]:
github.com/outcaste-io/badger/v3.(*memTable).IncrRef(...)
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/memtable.go:229
github.com/outcaste-io/badger/v3.(*DB).getMemTables(0xc0000e2480)
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/db.go:696 +0x12b
github.com/outcaste-io/badger/v3.(*DB).get(0xc0000e2480, {0xc009a5fa70, 0xc00fe67ec0, 0x2e56bf})
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/db.go:730 +0xac
github.com/outcaste-io/badger/v3.(*Txn).Get(0xc000345100, {0xc00c7cda40, 0x20, 0x1})
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/txn.go:498 +0x265
storj.io/gateway-mt/pkg/auth/badgerauth.lookupRecord(0x30, {0xe7, 0xd2, 0xea, 0x7b, 0x61, 0x30, 0xe0, 0x55, 0xad, ...})
        /go/build/pkg/auth/badgerauth/db.go:401 +0x67
storj.io/gateway-mt/pkg/auth/badgerauth.(*DB).findResponseEntries.func1(0xc0000e2480)
        /go/build/pkg/auth/badgerauth/db.go:262 +0x38f
github.com/outcaste-io/badger/v3.(*DB).View(0x30, 0xc000499a38)
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/txn.go:826 +0x9c
...
```

Full trace:

<details><pre>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9e4feb]
goroutine 5401444 [running]:
github.com/outcaste-io/badger/v3.(*memTable).IncrRef(...)
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/memtable.go:229
github.com/outcaste-io/badger/v3.(*DB).getMemTables(0xc0000e2480)
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/db.go:696 +0x12b
github.com/outcaste-io/badger/v3.(*DB).get(0xc0000e2480, {0xc009a5fa70, 0xc00fe67ec0, 0x2e56bf})
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/db.go:730 +0xac
github.com/outcaste-io/badger/v3.(*Txn).Get(0xc000345100, {0xc00c7cda40, 0x20, 0x1})
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/txn.go:498 +0x265
storj.io/gateway-mt/pkg/auth/badgerauth.lookupRecord(0x30, {0xe7, 0xd2, 0xea, 0x7b, 0x61, 0x30, 0xe0, 0x55, 0xad, ...})
        /go/build/pkg/auth/badgerauth/db.go:401 +0x67
storj.io/gateway-mt/pkg/auth/badgerauth.(*DB).findResponseEntries.func1(0xc0000e2480)
        /go/build/pkg/auth/badgerauth/db.go:262 +0x38f
github.com/outcaste-io/badger/v3.(*DB).View(0x30, 0xc000499a38)
        /go/pkg/mod/github.com/outcaste-io/badger/v3@v3.2202.1-0.20220409155652-232f5040a908/txn.go:826 +0x9c
storj.io/gateway-mt/pkg/auth/badgerauth.(*DB).findResponseEntries(0x4b3f9c, {0x65, 0x75, 0x2d, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /go/build/pkg/auth/badgerauth/db.go:243 +0x8d
storj.io/gateway-mt/pkg/auth/badgerauth.(*Node).Replicate(0xc000358640, {0xe06aa0, 0xc00a1fa7c0}, 0xc00a1fa7c0)
        /go/build/pkg/auth/badgerauth/node.go:208 +0x1a5
storj.io/gateway-mt/pkg/auth/badgerauth/pb.DRPCReplicationServiceDescription.Method.func2({0xe99440, 0xc000358640}, {0x1021480, 0xc0107f9b00}, {0xe06aa0, 0xc00a1fa7c0}, {0xc0049a6ec0, 0xc012146de0})
        /go/build/pkg/auth/badgerauth/pb/badgerauth_drpc.pb.go:107 +0x78
storj.io/drpc/drpcmux.(*Mux).HandleRPC(0xc000342600, {0x1028338, 0xc0107f9b00}, {0xc012146de0, 0x28})
        /go/pkg/mod/storj.io/drpc@v0.0.30/drpcmux/handle_rpc.go:33 +0x22d
storj.io/drpc/drpcserver.(*Server).handleRPC(0xc00c2571e0, 0x1020ca0, {0xc012146de0, 0x170dfc8})
        /go/pkg/mod/storj.io/drpc@v0.0.30/drpcserver/server.go:122 +0x42
storj.io/drpc/drpcserver.(*Server).ServeOne(0xc000518f00, {0x1021448, 0xc000212e10}, {0x7fbe22709480, 0xc00c348000})
        /go/pkg/mod/storj.io/drpc@v0.0.30/drpcserver/server.go:66 +0x1db
storj.io/drpc/drpcserver.(*Server).Serve.func2({0x1021448, 0xc000212e10})
        /go/pkg/mod/storj.io/drpc@v0.0.30/drpcserver/server.go:112 +0x58
storj.io/drpc/drpcctx.(*Tracker).track(0xc000212e10, 0xc003ccddd0)
        /go/pkg/mod/storj.io/drpc@v0.0.30/drpcctx/transport.go:52 +0x2b
created by storj.io/drpc/drpcctx.(*Tracker).Run
        /go/pkg/mod/storj.io/drpc@v0.0.30/drpcctx/transport.go:47 +0x92
</pre></details>

I can't confirm this now, but this might have happened when BadgerDB was shutting down. Specifically, it looks like the memory table was already flushed, but the database still allowed a read to happen. Should there be additional locking there? I can try to fix this if someone more familiar with this part of the code can confirm whether I'm onto something.

**Comment by amwolff** [comment]
@manishrjain Sorry for a direct ping; I thought you would know the best what could have happened there (as I mentioned, I'm happy to try to fix this!).

**Comment by manishrjain** [comment]
Hey @amwolff ,

The Badger fork I have no longer uses a memTable. So, this isn't relevant to this fork.
