### ISSUE TITLE
Future of badger?

### ISSUE THREAD

**Issue by morphar** [outcaste-io/issues#28]
Hi @manishrjain :)

I have been using Badger for some time now and switched to the outcaste-io as soon as you forked.
I just noticed that you archived the repository and mentions that it has moved to outserv repo.
What does that mean for Badger's future?
Outserv repo is not public, right? Will it be?

I have really enjoyed using Badger and hope that I can continue using it.
What are the plans?

**Comment by manishrjain** [comment]
Hey @morphar ,

I have deleted around 25% of the Badger code, keeping only the most important APIs relevant to Outserv. I'm still using and working on and improving Badger, but on this "lighter" reduced version.

Outserv would be launching this month, and would be public. Have a look at the APIs -- if you think these APIs are useful, you can continue to use this Badger fork. Indeed if enough people want to use this fork, we can consider bringing this fork back.

Cheers,
Manish

**Comment by morphar** [comment]
Hey @manishrjain,

Awesome! :)

Yeah, I noticed that you were removing a lot of stuff 👍 
I think my use case will benefit from your work on shrinking the database, as I'm already using it managed.
And the way write transactions work(ed), was not optimal for my use case, so I did some book keeping and workarounds.
I'm not sure this has actually changed? It just seemed so, when I glanced over the pull request and the write batch stuff? :)

So I think, the only thing I need to fully understand, to know if I can keep using Badger, is the value log work.
I assume it has nothing to do with actually storing the values on disk, right? That's done in the wal and sstable files, is that correct?
Anyway, I will try the latest commit soon and see if everything still works :)

Cheers
Dan

**Comment by veith** [comment]
I hope this will not cause a lot of breaking changes 👍 

And that is the moment where i will see that i have written enough (and the relevant) tests on my project. :-)

**Comment by evanoberholster** [comment]
For my use I would prefer a reduced version of badger. Would it be possible to keep this fork updated instead of archive?

**Comment by manishrjain** [comment]
Alright. Sure, can do. The repo is unarchived. I can have some of the maintainers copy over changes made in Outserv here every few months.

**Comment by morphar** [comment]
Much appreciated @manishrjain 👍 
Though I would happily use a version of badger from something like a pkg in outserv, as long as it the usage of was the same - e.g. `import github.com/outserver/pkg/badger` and use as now :)

What exactly does `leaner` mean with regards to no Value Log and Write Ahead?
Is the writes done directly to SSTables instead of first WAL and Value log and then continuously written to SSTables?
Is there anything we need to be aware of with regards to ACID, etc?
